# Generated by Django 2.1 on 2020-01-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='occupants_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
